name: nutrinote
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ui
  convex_bottom_bar: ^3.1.0+1

  #utils
  go_router: ^6.0.0
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  flutter_secure_storage: ^8.0.0
  dio: ^5.0.1
  auto_size_text: ^3.0.0
  fluttertoast: ^8.1.2
  uuid: ^3.0.7
  clipboard: ^0.1.3
  form_field_validator: ^1.1.0
  share_plus: ^6.3.0
  image_picker: ^0.8.6
  flutter_svg: ^2.0.2
  flutter_launcher_icons: ^0.11.0
  flex_color_scheme: ^6.1.2
  openfoodfacts: 

  #firebase
  firebase_core:
  firebase_crashlytics:
  firebase_analytics:
  firebase_performance:
  firebase_storage:
  firebase_dynamic_links:
  firebase_auth:
  firebase_database:

  #annotation
  json_annotation: ^4.7.0
  json_serializable: ^6.6.0
  copy_with_extension_gen: ^5.0.0

  # state
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  shared_preferences:
  equatable:
  meta: ^1.3.0
  very_good_analysis: ^4.0.0+1
  flutter_form_builder: ^7.4.0
  form_builder_validators: ^8.2.0

  #ui
  simple_circular_progress_bar: ^1.0.2
  weekly_date_picker: ^1.3.0
  font_awesome_flutter:
    git:
      url: https://github.com/ColtonDevAcc/fa_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
