// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuMcvI-KRsDtdq9dUHMhmIkyni4UBnWjM',
    appId: '1:96874525266:web:e86ef37bb5ecff22d1658b',
    messagingSenderId: '96874525266',
    projectId: 'nutrinote-7daa5',
    authDomain: 'nutrinote-7daa5.firebaseapp.com',
    storageBucket: 'nutrinote-7daa5.appspot.com',
    measurementId: 'G-EZS3Z3DF82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIK8TbsDBsxHBtcnEEQhRhfM29FyXLbNs',
    appId: '1:96874525266:android:d71e3f7b8fa021bfd1658b',
    messagingSenderId: '96874525266',
    projectId: 'nutrinote-7daa5',
    storageBucket: 'nutrinote-7daa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaJYfUFXLw7Mk2KX0CF1Tp68rqlcv1QUo',
    appId: '1:96874525266:ios:81de494e86112763d1658b',
    messagingSenderId: '96874525266',
    projectId: 'nutrinote-7daa5',
    storageBucket: 'nutrinote-7daa5.appspot.com',
    iosClientId: '96874525266-diu2853tctonut2otto89fqequcoj7rr.apps.googleusercontent.com',
    iosBundleId: 'com.voostack.nutrinote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaJYfUFXLw7Mk2KX0CF1Tp68rqlcv1QUo',
    appId: '1:96874525266:ios:81de494e86112763d1658b',
    messagingSenderId: '96874525266',
    projectId: 'nutrinote-7daa5',
    storageBucket: 'nutrinote-7daa5.appspot.com',
    iosClientId: '96874525266-diu2853tctonut2otto89fqequcoj7rr.apps.googleusercontent.com',
    iosBundleId: 'com.voostack.nutrinote',
  );
}
