// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9vi8HuQ9nHWxZLCRuoTod3XB1ocTwhco',
    appId: '1:837772000358:web:1b97dabae34fa4447641a7',
    messagingSenderId: '837772000358',
    projectId: 'nutrinote-375816',
    authDomain: 'nutrinote-375816.firebaseapp.com',
    storageBucket: 'nutrinote-375816.appspot.com',
    measurementId: 'G-V70DTK0NQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIhJ-_beyQNk26q_TNs95WFz2l04nC0lY',
    appId: '1:837772000358:android:81e371849b8bb6d47641a7',
    messagingSenderId: '837772000358',
    projectId: 'nutrinote-375816',
    storageBucket: 'nutrinote-375816.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGI-iQtWEp_2a7c3Hj4CZIvgU3zS-VqKY',
    appId: '1:837772000358:ios:00af8efda8b348e17641a7',
    messagingSenderId: '837772000358',
    projectId: 'nutrinote-375816',
    storageBucket: 'nutrinote-375816.appspot.com',
    iosClientId: '837772000358-mqmiph8qp8iob2njv8saehq6onbq7n1p.apps.googleusercontent.com',
    iosBundleId: 'com.voostack.nutrinote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGI-iQtWEp_2a7c3Hj4CZIvgU3zS-VqKY',
    appId: '1:837772000358:ios:00af8efda8b348e17641a7',
    messagingSenderId: '837772000358',
    projectId: 'nutrinote-375816',
    storageBucket: 'nutrinote-375816.appspot.com',
    iosClientId: '837772000358-mqmiph8qp8iob2njv8saehq6onbq7n1p.apps.googleusercontent.com',
    iosBundleId: 'com.voostack.nutrinote',
  );
}
